sudo: required

services: docker

before_install:
  - gem install bundler -v 2.2.33
  - bundle config set --local deployment 'true'
  - bundle config set --local jobs 3
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test