sudo: required

services: docker

language: ruby
rvm:
  - 3.0

before_install:
  - gem install bundler -v 2.2.33
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test